#  NumPy (Numerical Python)

+ NumPy is a fundamental package for scientific (numeric) computing with Python.     
+ It allows us to create, store and manipulate data.  
+ It is the foundation that Pandas package is built on.   
+ It support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays, like min(), max(), etc.   
+ It was created by Jim Hugunin, and was released in 1995. 

In [3]:
import numpy #importing it.
import math

In [4]:
import numpy as np   #generally np is used as abbreviation for numpy.

In [7]:
a = np.array([1,2,3])   #to create an array I have used array() function and notice that I have added a list into that function,
                        #that will be our array. 
print(a)

[1 2 3]


In [8]:
a.ndim   #to check the dimension of the array. 

1

In [9]:
a.dtype  #tells the type of elements in the array.  

dtype('int32')

In [14]:
#creating a multi-dimensional array. 
#We can pass a list of lists for this into the array() function.   
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
2
int32


In [16]:
#now checking the shape of our array.
#it returns a tuple. 
b.shape    

(2, 3)