#  NumPy (Numerical Python)

+ NumPy is a fundamental package for scientific (numeric) computing with Python.     
+ It allows us to create, store and manipulate data.  
+ It is the foundation that Pandas package is built on.   
+ It support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays, like min(), max(), etc.   
+ It was created by Jim Hugunin, and was released in 1995. 

### Installing, importing, creating arrays, etc. 

In [21]:
#use this command in cmd to download and install the numpy package
# "pip install numpy"

In [3]:
import numpy #importing it.
import math

In [4]:
import numpy as np   #generally np is used as abbreviation for numpy.

In [7]:
a = np.array([1,2,3])   #to create an array I have used array() function and notice that I have added a list into that function,
                        #that will be our array. 
print(a)

[1 2 3]


In [8]:
a.ndim   #to check the dimension of the array. 

1

In [9]:
a.dtype  #tells the type of elements in the array.  

dtype('int32')

In [14]:
#creating a multi-dimensional array. 
#We can pass a list of lists for this into the array() function.   
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
2
int32


In [16]:
#now checking the shape of our array.
#it returns a tuple. 
b.shape    

(2, 3)

In [18]:
c = np.array([2.2, 5, 1.1])
print(c.dtype)
print(c)  

#notice that numpy automatically converted the element 5 into a floating point number.
# It tries to maintain the homogeneity of our array. 

float64
[2.2 5.  1.1]


In [22]:
#other ways to create arrays. 
d = np.zeros((2,3)) # an array with all elements that are 0. We have to  pass the shape as an argument in the function. 
e = np.ones((2,3))  #an array with all elements that are 1. We have to  pass the shape as an argument in the function.

print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#generating an array with random numbers:
np.random.rand(2,3)

array([[0.67882369, 0.32388559, 0.53153806],
       [0.73717815, 0.28627471, 0.4530464 ]])

In [28]:
#Now, I am going to generate a sequence of numbers as an array, using the arange() function. The first argument is the starting number, 
#second argument is the ending number and the third argument is the difference between each consecutive numbers. 
#The default third argument is 1. 

f = np.arange(10, 50, 2)    #10 is inclusive, 50 is exclusive. 
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [32]:
#Now, I am going to generate a sequence of floats as an array, using the linspace() function. The first argument is the starting bound, 
#second argument is the ending bound and the third argument is the number of elements we cant between them. 
#The default third argument is 1. 

g = np.linspace(1, 2, 20)    #20 numbers from 1 (inclusive) to 2 (inclusive). 
print(g)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


### Arithmetic Operations

In [46]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(b**2)

#boolean 
#gives arrays with boolean True & False
print(a>20)
print(a<10)
print(b!=4)
print(a%2 == 0)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 1  4  9 16]
[False False  True  True]
[False False False False]
[ True  True  True False]
[ True  True  True  True]


In [45]:
#I have created two matrices. 
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A*B) # asterisk * is used for element wise multiplication. 
print(A@B) # at sign @ is used for dot product.


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [47]:
#UPCASTING 
#while manipulating two arrays, the resulting array will correspond to the more general of the two types. This is called as Upcasting.  

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2.0, 1.0, 4.5], [3.4, 4.5, 2.0]])

print(A.dtype)
print(B.dtype)
print((A+B).dtype)
#we can see that the result is float type. 

int32
float64
float64


In [50]:
#Aggregation functions

A = np.array([1, 2, 3, 4, 5, 6])

print(A.min())
print(A.max())
print(A.sum())
print(A.mean())


1
6
21
3.5


In [52]:
a=np.arange(1,16,1).reshape(3,5)   #I have reshaped it immediately. Note that it will ony work if the reshaping and creating array both 
                                   #have same number of elements. That is 15. So, 3*5=15. 
print(a)    

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Indexing, Slicing & Iterating